# Docker Compose configuration for local development and testing
version: '3'

services:
  sudoku-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
